---
title: "Cleaning Script"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Package Loading

```{r}
library(tidyverse)
```

# Data Loading

```{r}
stakeholder_survey <- read.csv("/Users/kenjinchang/github/scr-and-stakeholder-analysis/data/survey-data.csv")
```

# Cleaning

```{r}
stakeholder_survey <- stakeholder_survey %>%
  select(RecordedDate,Progress,DistributionChannel,Q1,Q2,Q2_4_TEXT,Q6,Q6_10_TEXT,Q3,Q5_1,Q2_1,Q2_2,Q2_3,Q2_4,Q2_5,Q2_6,Q2_7,Q2_8,Q2_9,Q2_9_TEXT) %>%
  rename(data=RecordedDate,completion=Progress,channel=DistributionChannel,consent=Q1,involvement=Q2,involvement_other=Q2_4_TEXT,role_type=Q6,role_type_other=Q6_10_TEXT,title=Q3,role_duration=Q5_1,dietary_health_ranking=Q2_1,dietary_sustainability_ranking=Q2_2,institutional_sustainability_ranking=Q2_3,food_pricing_ranking=Q2_4,operational_costs_ranking=Q2_5,guest_satisfaction_ranking=Q2_6,worker_satisfaction_ranking=Q2_7,campus_culture_ranking=Q2_8,other_ranking=Q2_9,other_ranking_other=Q2_9_TEXT) %>%
  slice(3:n()) %>%
  mutate(dietary_health_ranking=as.numeric(dietary_health_ranking)) %>%
  mutate(dietary_sustainability_ranking=as.numeric(dietary_sustainability_ranking)) %>%
  mutate(institutional_sustainability_ranking=as.numeric(institutional_sustainability_ranking)) %>%
  mutate(food_pricing_ranking=as.numeric(food_pricing_ranking)) %>%
  mutate(operational_costs_ranking=as.numeric(operational_costs_ranking)) %>%
  mutate(guest_satisfaction_ranking=as.numeric(guest_satisfaction_ranking)) %>%
  mutate(worker_satisfaction_ranking=as.numeric(worker_satisfaction_ranking)) %>%
  mutate(campus_culture_ranking=as.numeric(campus_culture_ranking)) %>%
  mutate(other_ranking=as.numeric(other_ranking)) %>%
  mutate(dietary_health_score=case_when(dietary_health_ranking == 1 ~ 9,
                                        dietary_health_ranking == 2 ~ 8,
                                        dietary_health_ranking == 3 ~ 7,
                                        dietary_health_ranking == 4 ~ 6,
                                        dietary_health_ranking == 5 ~ 5,
                                        dietary_health_ranking == 6 ~ 4,
                                        dietary_health_ranking == 7 ~ 3,
                                        dietary_health_ranking == 8 ~ 2,
                                        dietary_health_ranking == 9 ~ 1)) %>%
  mutate(dietary_sustainability_score=case_when(dietary_sustainability_ranking == 1 ~ 9,
                                        dietary_sustainability_ranking == 2 ~ 8,
                                        dietary_sustainability_ranking == 3 ~ 7,
                                        dietary_sustainability_ranking == 4 ~ 6,
                                        dietary_sustainability_ranking == 5 ~ 5,
                                        dietary_sustainability_ranking == 6 ~ 4,
                                        dietary_sustainability_ranking == 7 ~ 3,
                                        dietary_sustainability_ranking == 8 ~ 2,
                                        dietary_sustainability_ranking == 9 ~ 1)) %>%
  mutate(institutional_sustainability_score=case_when(institutional_sustainability_ranking == 1 ~ 9,
                                        institutional_sustainability_ranking == 2 ~ 8,
                                        institutional_sustainability_ranking == 3 ~ 7,
                                        institutional_sustainability_ranking == 4 ~ 6,
                                        institutional_sustainability_ranking == 5 ~ 5,
                                        institutional_sustainability_ranking == 6 ~ 4,
                                        institutional_sustainability_ranking == 7 ~ 3,
                                        institutional_sustainability_ranking == 8 ~ 2,
                                        institutional_sustainability_ranking == 9 ~ 1)) %>%
  mutate(food_pricing_score=case_when(food_pricing_ranking == 1 ~ 9,
                                        food_pricing_ranking == 2 ~ 8,
                                        food_pricing_ranking == 3 ~ 7,
                                        food_pricing_ranking == 4 ~ 6,
                                        food_pricing_ranking == 5 ~ 5,
                                        food_pricing_ranking == 6 ~ 4,
                                        food_pricing_ranking == 7 ~ 3,
                                        food_pricing_ranking == 8 ~ 2,
                                        food_pricing_ranking == 9 ~ 1)) %>%
  mutate(operational_costs_score=case_when(operational_costs_ranking == 1 ~ 9,
                                        operational_costs_ranking == 2 ~ 8,
                                        operational_costs_ranking == 3 ~ 7,
                                        operational_costs_ranking == 4 ~ 6,
                                        operational_costs_ranking == 5 ~ 5,
                                        operational_costs_ranking == 6 ~ 4,
                                        operational_costs_ranking == 7 ~ 3,
                                        operational_costs_ranking == 8 ~ 2,
                                        operational_costs_ranking == 9 ~ 1)) %>%
  mutate(guest_satisfaction_score=case_when(guest_satisfaction_ranking == 1 ~ 9,
                                        guest_satisfaction_ranking == 2 ~ 8,
                                        guest_satisfaction_ranking == 3 ~ 7,
                                        guest_satisfaction_ranking == 4 ~ 6,
                                        guest_satisfaction_ranking == 5 ~ 5,
                                        guest_satisfaction_ranking == 6 ~ 4,
                                        guest_satisfaction_ranking == 7 ~ 3,
                                        guest_satisfaction_ranking == 8 ~ 2,
                                        guest_satisfaction_ranking == 9 ~ 1)) %>%
  mutate(worker_satisfaction_score=case_when(worker_satisfaction_ranking == 1 ~ 9,
                                        worker_satisfaction_ranking == 2 ~ 8,
                                        worker_satisfaction_ranking == 3 ~ 7,
                                        worker_satisfaction_ranking == 4 ~ 6,
                                        worker_satisfaction_ranking == 5 ~ 5,
                                        worker_satisfaction_ranking == 6 ~ 4,
                                        worker_satisfaction_ranking == 7 ~ 3,
                                        worker_satisfaction_ranking == 8 ~ 2,
                                        worker_satisfaction_ranking == 9 ~ 1)) %>%
  mutate(campus_culture_score=case_when(campus_culture_ranking == 1 ~ 9,
                                        campus_culture_ranking == 2 ~ 8,
                                        campus_culture_ranking == 3 ~ 7,
                                        campus_culture_ranking == 4 ~ 6,
                                        campus_culture_ranking == 5 ~ 5,
                                        campus_culture_ranking == 6 ~ 4,
                                        campus_culture_ranking == 7 ~ 3,
                                        campus_culture_ranking == 8 ~ 2,
                                        campus_culture_ranking == 9 ~ 1)) %>%
  mutate(other_score=case_when(other_ranking == 1 ~ 9,
                                        other_ranking == 2 ~ 8,
                                        other_ranking == 3 ~ 7,
                                        other_ranking == 4 ~ 6,
                                        other_ranking == 5 ~ 5,
                                        other_ranking == 6 ~ 4,
                                        other_ranking == 7 ~ 3,
                                        other_ranking == 8 ~ 2,
                                        other_ranking == 9 ~ 1)) 
```

```{r}
stakeholder_survey
```


```{r}
stakeholder_survey %>%
  group_by(role_type) %>%
  summarise(dietary_health_score_mean=mean(dietary_health_score),dietary_sustainability_score_mean=mean(dietary_sustainability_score),institutional_sustainability_score_mean=mean(institutional_sustainability_score),institutional_sustainability_score_mean=mean(institutional_sustainability_score),food_pricing_score_mean=mean(food_pricing_score),operational_costs_score_mean=mean(operational_costs_score),guest_satisfaction_score_mean=mean(guest_satisfaction_score),worker_satisfaction_score_mean=mean(worker_satisfaction_score),campus_culture_score_mean=mean(campus_culture_score),other_score_mean=mean(other_score),n=n())
```


```{r}
stakeholder_survey %>%
  summarise(dietary_health_score_mean=mean(dietary_health_score),dietary_sustainability_score_mean=mean(dietary_sustainability_score),institutional_sustainability_score_mean=mean(institutional_sustainability_score),institutional_sustainability_score_mean=mean(institutional_sustainability_score),food_pricing_score_mean=mean(food_pricing_score),operational_costs_score_mean=mean(operational_costs_score),guest_satisfaction_score_mean=mean(guest_satisfaction_score),worker_satisfaction_score_mean=mean(worker_satisfaction_score),campus_culture_score_mean=mean(campus_culture_score),other_score_mean=mean(other_score),n=n())
```
```{r}
stakeholder_survey %>%
  summarise(dietary_health_score_sum=sum(dietary_health_score),dietary_sustainability_score_sum=sum(dietary_sustainability_score),institutional_sustainability_score_sum=sum(institutional_sustainability_score),institutional_sustainability_score_sum=sum(institutional_sustainability_score),food_pricing_score_sum=sum(food_pricing_score),operational_costs_score_sum=sum(operational_costs_score),guest_satisfaction_score_sum=sum(guest_satisfaction_score),worker_satisfaction_score_sum=sum(worker_satisfaction_score),campus_culture_score_sum=sum(campus_culture_score),other_score_sum=sum(other_score),n=n())
```
